---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Install
```{r}
install.packages("textshape")
install.packages("pheatmap")
BiocManager::install("UniProt.ws")
install.packages("enrichR")
```

# Import

```{r}
library(textshape)
library(pheatmap)
library(UniProt.ws)
library(enrichR)
```

# Heatmap

```{r}
df <- read.csv("~/CPM_Paper_Reproduction/data/forCorrelation.csv", header = TRUE)
rownames(df) <- df[, 1]
df <- df[, -1]

# Calculate correlations
cor_df <- cor(t(df[, ]), method = "pearson")

# Cluster and order the data frame
ordered_cor_df <- cluster_matrix(cor_df, dim = "both", method = "average")

# Plot the heat-map
pheatmap(ordered_cor_df,
         color = colorRampPalette(c("#4d72af", "white", "#c44e53")) (101),
         breaks = seq(from = -1, to = 1, length.out = 101),
         border_color = NA,legend = FALSE, show_colnames = FALSE, 
         show_rownames = FALSE,
         cluster_rows = FALSE, cluster_cols = FALSE,
         cellwidth = 0.3, cellheight = 0.3,
         fontfamily = 'sans',fontsize = 10)
```

# Identify Clusters

```{r}
distance_df <- 1 - cor_df

tree <-  hclust(as.dist(distance_df), method = "average")

memberships <- cutreeDynamic(tree)

memberships <- as.data.frame(memberships)
```

# Enrichment

```{r}
# Choose a cluster
cluster_members <- rownames(cor_df)[memberships$memberships == 1]

# Map to Gene names
up <- UniProt.ws(taxId=9606)
res <- select(
    x = up,
    keys = cluster_members,
    to = "Gene_Name"
)

# List of databases: View(listEnrichrDbs())

dbs <- c("WikiPathway_2023_Human", "GO_Biological_Process_2023", "KEGG_2021_Human")
enriched <- enrichr(res$To, dbs)
plotEnrich(enriched[[1]], showTerms = 20, numChar = 40, y = "Ratio", orderBy = "P.value")
```
